# Generated by Django 4.0.4 on 2022-04-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='cantidad_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productos',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
